"""
Ring Detection Engine — Phase 1 Rule-Based (5 signals)
Catches coordinated fraud rings without requiring ML training data.
Phase 3 will bootstrap GraphSAGE GNN on labels generated by this system.
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
import asyncio
from models.graph_detector import graph_detector

router = APIRouter()


class RingDetectRequest(BaseModel):
    worker_id: str
    trigger_event_id: str
    # Optional context signals from the claim
    claim_timestamp_unix: Optional[int] = None
    zone_cell_500m: Optional[str] = None  # Geo-cell hash
    referral_code: Optional[str] = None
    device_fingerprint: Optional[str] = None
    ip_subnet: Optional[str] = None


class RingDetectResponse(BaseModel):
    ring_detected: bool
    confidence: float
    gnn_ring_prob: float
    signals_triggered: list[str]
    cluster_id: Optional[str] = None


# In-memory ring signal store (Redis in production)
_claim_log: list[dict] = []


@router.post("/detect", response_model=RingDetectResponse)
async def detect_ring(req: RingDetectRequest) -> RingDetectResponse:
    """
    Runs 5 ring detection signals on a new claim.
    Returns ring_detected=True if 2+ signals fire simultaneously.
    """
    signals_triggered: list[str] = []
    confidence = 0.0

    # Log this claim for real-time cross-claim analysis
    _claim_log.append({
        "worker_id": req.worker_id,
        "trigger_event_id": req.trigger_event_id,
        "timestamp": req.claim_timestamp_unix,
        "zone_cell": req.zone_cell_500m,
        "referral_code": req.referral_code,
        "device_fp": req.device_fingerprint,
        "ip_subnet": req.ip_subnet,
    })

    # Keep only last 1000 claims in memory (Redis in production)
    if len(_claim_log) > 1000:
        _claim_log.pop(0)

    # --- Signal R1: Temporal Clustering (Telegram Heartbeat) ---
    # Count claims in same trigger_event within last 10 minutes
    if req.claim_timestamp_unix and req.trigger_event_id:
        recent_same_trigger = [
            c for c in _claim_log
            if c["trigger_event_id"] == req.trigger_event_id
            and abs((c.get("timestamp") or 0) - req.claim_timestamp_unix) < 600  # 10 min
        ]
        if len(recent_same_trigger) > 30:  # >30 claims in 10 min on same trigger
            signals_triggered.append("R1_TEMPORAL_CLUSTERING")
            confidence += 0.3

    # --- Signal R2: Social Graph Proximity ---
    if req.referral_code:
        same_referral = [
            c for c in _claim_log
            if c.get("referral_code") == req.referral_code
            and c["worker_id"] != req.worker_id
        ]
        if len(same_referral) >= 9:  # 10+ people from same referral chain
            signals_triggered.append("R2_REFERRAL_CHAIN_CLUSTER")
            confidence += 0.25

    # --- Signal R3: Behavioral Homogeneity ---
    # If 20+ claims came in with exactly similar timing patterns on same trigger
    if req.trigger_event_id and req.claim_timestamp_unix:
        trigger_claims = [
            c for c in _claim_log
            if c["trigger_event_id"] == req.trigger_event_id
        ]
        if len(trigger_claims) >= 20:
            timestamps = [c.get("timestamp", 0) for c in trigger_claims if c.get("timestamp")]
            if timestamps:
                std_dev = _std_dev(timestamps)
                # Very tight clustering = scripted (std dev < 60 seconds over 20+ claims)
                if std_dev < 60 and len(timestamps) >= 20:
                    signals_triggered.append("R3_BEHAVIORAL_HOMOGENEITY")
                    confidence += 0.2

    # --- Signal R4: Velocity Anomaly (First-Timer Attack) ---
    # New account claiming within 8 minutes of trigger
    first_ever_claim = not any(
        c["worker_id"] == req.worker_id for c in _claim_log[:-1]
    )
    if first_ever_claim and req.claim_timestamp_unix:
        signals_triggered.append("R4_FIRST_TIMER_VELOCITY")
        confidence += 0.15

    # --- Signal R5: Network Co-location ---
    if req.ip_subnet:
        same_ip = [
            c for c in _claim_log
            if c.get("ip_subnet") == req.ip_subnet
            and c["worker_id"] != req.worker_id
        ]
        if len(same_ip) >= 4:  # 5+ claims from same IP subnet
            signals_triggered.append("R5_NETWORK_COLOCATION")
            confidence += 0.35

    # Phase 3: GNN Signal Integration
    # Create a synthetic node_data cluster from recent claims in the same zone
    cluster_node_data = []
    # Identify colleagues in same zone_cell within last 30 min
    colleagues = [
        c for c in _claim_log
        if c.get("zone_cell") == req.zone_cell_500m
        and req.claim_timestamp_unix
        and abs((c.get("timestamp") or 0) - req.claim_timestamp_unix) < 1800
    ]
    
    for c in colleagues:
        # In a real system, we'd fetch these from a feature store (Redis)
        # For now, we'll use the data if available or defaults
        cluster_node_data.append({
            "id": c["worker_id"],
            "age": 10,     # New accounts in rings
            "bcs": 20,     # Low BCS for ring accounts
            "ratio": 0.4,  # High payout ratio
            "neighbors": [other["worker_id"] for other in colleagues if other["worker_id"] != c["worker_id"]]
        })
    
    gnn_prob = graph_detector.detect_ring_in_cluster(cluster_node_data) if len(cluster_node_data) > 1 else 0.0

    # Final combined logic
    ring_detected = confidence >= 0.4 or len(signals_triggered) >= 2 or gnn_prob > 0.7
    cluster_id = f"ring_{req.trigger_event_id[:8]}_{req.zone_cell_500m or 'unk'}" if ring_detected else None

    return RingDetectResponse(
        ring_detected=ring_detected,
        confidence=round(min(1.0, confidence), 3),
        gnn_ring_prob=round(gnn_prob, 3),
        signals_triggered=signals_triggered,
        cluster_id=cluster_id,
    )


def _std_dev(values: list[float]) -> float:
    if len(values) < 2:
        return 0.0
    mean = sum(values) / len(values)
    variance = sum((v - mean) ** 2 for v in values) / len(values)
    return variance ** 0.5
